### ISSUE TITLE
Global installation broken

### ISSUE THREAD

**Issue by shinglyu** [artilleryio/artillery#1019]
## Step to reproduce:
* Install using `npm install -g artillery`
* Run `artillery run quick --count 20 --num 100 http://localhost:3000/`

## Expected: 
The command should run
## Actual:
Failed with 
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'cheerio'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.24.1/lib/node_modules/artillery/core/lib/engine_util.js:15:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
## Environment
OS: Amazon Linux 2 (docker base image)
Node version: failed in both v10.24.1 and v14

**Comment by shinglyu** [comment]
It start to break roughly 20 min ago, which corresponds to a new RC release of cheerio (https://github.com/cheeriojs/cheerio/releases). Maybe the version is not locked?

**Comment by shinglyu** [comment]
Oh OK cheerio released two broken release rc7 and rc8. Now with rc9 it's fixed. Maybe it's better to lock the dependency version in releases?

**Comment by hassy** [comment]
Thank you @shinglyu! SemVer ranges strike again! 😄 created #1020
