### ISSUE TITLE
Error if output flag is specified as a directory

### ISSUE THREAD

**Issue by chringwer** [artilleryio/artillery#1285]
It seems that specifying a directory via the output flag is supported but in that case the filename would be generated using `moment.js` which isn't required properly: 
https://github.com/artilleryio/artillery/blob/026bdbc520be8dd45a03e0c7504f5955c86b3c5c/lib/cmds/run.js#L412

```
(node:10806) UnhandledPromiseRejectionWarning: ReferenceError: moment is not defined
    at getLogFilename (/project-root/node_modules/artillery/lib/cmds/run.js:385:7)
    at EventEmitter.<anonymous> (/project-root/node_modules/artillery/lib/cmds/run.js:98:25)
    at EventEmitter.emit (/project-root/node_modules/eventemitter3/index.js:202:33)
    at EventEmitter.<anonymous> (/project-root/node_modules/artillery/lib/launch-local.js:257:23)
```

**Comment by hassy** [comment]
thank you @chringwer, sure seems like a bug! 🐛
