### ISSUE TITLE
Generating reports in Docker - error

### ISSUE THREAD

**Issue by sterankin** [artilleryio/artillery#1482]
Version info:
```
Artillery Core: 2.0.0-18
Node.js: v17.8.0
```

Running this command: 
```
docker run  --rm  --volume ${PWD}/testing-apis/artillery:/usr/src/app artilleryio/artillery:latest run /usr/src/app/artillery-config.yml --output /usr/src/app/result.json && artillery report --output /usr/src/app/report.html /usr/src/app/result.json
```

I expected to see this happen:

HTML report would be generated.

Instead, this happened:

```
Log file: /usr/src/app/result.json
    Error: ENOENT: no such file or directory, open 'result.json'
    Code: ENOENT
Error: ENOENT: no such file or directory, open 'result.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at ReportCommand.run (/usr/local/lib/node_modules/artillery/lib/cmds/report.js:13:32)
    at ReportCommand._run (/usr/local/lib/node_modules/artillery/node_modules/@oclif/command/lib/command.js:43:31)
ENOENT
ENOENT: no such file or directory, open 'result.json'
```

**Comment by hassy** [comment]
`artillery report` invoked after `&&` is running on the host I would guess, and not in the Docker container
