### ISSUE TITLE
Not able to run test script on AWS lambda

### ISSUE THREAD

**Issue by thminggg** [artilleryio/artillery#1566]
Going through the [AWS Lambda guide](https://www.artillery.io/blog/open-source-distributed-load-testing-with-lambda). Have all the AWS profile and IAM setup completed.

Version info: 
```
2.0.0-22
```

Running this command: 
```
curl -o blitz.yml   https://gist.githubusercontent.com/hassy/c723c93e2319449dd76f1602d81603da/raw/c6e71bc6e0041c095ef781e7c096192450c85410/blitz.yml
```
```
artillery run \
  --platform aws:lambda \
  --platform-opt region=us-east-1 \
  --count 25 \
  blitz.yml
```

I expected to see this happen:

Artillery creates a lambda function on my AWS account and run the script as if running in my local machine.

Instead, this happened:

An error prompted as shown below:
```
λ Creating AWS Lambda function...
    - Installing dependencies
    - Creating zip package
Preparing AWS environment...
⠸ /Users/<username>/.nvm/versions/node/v14.18.3/lib/node_modules/artillery/node_modules/aws-sdk/lib/protocol/json.js:52
  resp.error = util.error(new Error(), error);
                          ^

ValidationException: 'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008
    at Object.extractError (/Users/<username>/.nvm/versions/node/v14.18.3/lib/node_modules/artillery/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/Users/<username>/.nvm/versions/node/v14.18.3/lib/node_modules/artillery/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
    at Request.callListeners (/Users/<username>/.nvm/versions/node/v14.18.3/lib/node_modules/artillery/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/<username>/.nvm/versions/node/v14.18.3/lib/node_modules/artillery/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/<username>/.nvm/versions/node/v14.18.3/lib/node_modules/artillery/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/<username>/.nvm/versions/node/v14.18.3/lib/node_modules/artillery/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/<username>/.nvm/versions/node/v14.18.3/lib/node_modules/artillery/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/<username>/.nvm/versions/node/v14.18.3/lib/node_modules/artillery/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/<username>/.nvm/versions/node/v14.18.3/lib/node_modules/artillery/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/<username>/.nvm/versions/node/v14.18.3/lib/node_modules/artillery/node_modules/aws-sdk/lib/request.js:688:12) {
  code: 'ValidationException',
  time: 2022-08-08T09:52:07.399Z,
  requestId: '790980c0-4cc5-4cab-9dab-08726def489d',
  statusCode: 400,
  retryable: false,
  retryDelay: 16.069919232763507
}
```

**Comment by hassy** [comment]
This looks like an issue that needs to be resolved by contacting AWS support for the AWS account you're using: https://stackoverflow.com/questions/70943739/aws-lambda-memorysize-value-failed-to-satisfy-constraint

Artillery creates Lambdas with 4096MB of memory by default (https://github.com/artilleryio/artillery/blob/master/lib/platform/aws-lambda/index.js#L468) but the error message suggests that the limit in the AWS account you're using is 3008 MB.

**Comment by hassy** [comment]
Tagging this as "enhancement" because we can provide a friendlier error message when this happens.

**Comment by hassy** [comment]
The most recent release of Artillery supports customizing memory size with: `--platform-opt memory-size=3000` for example.
