### ISSUE TITLE
[Lambda] the role defined for the function cannot be assumed by Lambda.

### ISSUE THREAD

**Issue by philschmid** [artilleryio/artillery#1576]
Version info: 
```

        ___         __  _ ____
  _____/   |  _____/ /_(_) / /__  _______  __ ___
 /____/ /| | / ___/ __/ / / / _ \/ ___/ / / /____/
/____/ ___ |/ /  / /_/ / / /  __/ /  / /_/ /____/
    /_/  |_/_/   \__/_/_/_/\___/_/   \__  /
                                    /____/


VERSION INFO:

Artillery Core: 2.0.0-23
Artillery Pro:  not installed (https://artillery.io/product)

Node.js: v16.13.0
OS:      darwin
```

Running this command: 
```
artillery run \
  --platform aws:lambda \
  --platform-opt region=us-east-1 \
  --count 5 \
  --variables "{ \"token\": \"xxx\" }" \
  xxx.yaml
```

I expected to see this happen:

* Run load test on AWS Lambda
* Permission have admin access
* 
Instead, this happened:

* Got an error when trying to prepare AWS Environment

Error
```
λ Creating AWS Lambda function...
    - Installing dependencies
    - Creating zip package
Preparing AWS environment...
⠇ /usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/protocol/json.js:52
  resp.error = util.error(new Error(), error);
                          ^

InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.
    at Object.extractError (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
    at Request.callListeners (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/request.js:688:12) {
  code: 'InvalidParameterValueException',
  time: 2022-08-25T14:16:53.057Z,
  requestId: '0012ebed-7f87-4e7a-9c65-81c3eb44ed0f',
  statusCode: 400,
  retryable: false,
  retryDelay: 38.24056701013085
}
```

**Comment by hassy** [comment]
hi @philschmid 👋 

Could you check that the default IAM role named `artilleryio-default-lambda-role` was created successfully? (under IAM in the AWS Console for example)

Could you also try re-running the test if you only tried it once. It can sometimes take a minute or so for IAM changes to propagate after a role has been created for the first time.

**Comment by philschmid** [comment]
re-run it and then it worked. Thats strange something where it might be good to take an eye on

**Comment by hassy** [comment]
Good to know it worked! :) We may add a short wait when running a test for the first time to work around this.

If you have any feedback about the Lambda support please let us know!
