### ISSUE TITLE
SSL Client Certificate Auth - pro.isActivatedSync is not a function

### ISSUE THREAD

**Issue by elarrat** [artilleryio/artillery#1611]
Version info: 
```
2.0.0-23
```

I'm trying to send requests with ssl certificate, so I followed what the docs says:
- Installed artillery pro
- configured the `tls` section:
```
  tls:
    rejectUnauthorized: false
    client:
      cert: "./certs/staging-cert.pem"
      key: "./certs/staging-key.pem"
  plugins:
    http-ssl-auth: {}
```

And when I run `yarn artillery run mytest.yml` I get the following:

```
WARNING: Could not load plugin: http-ssl-auth warn
WARNING: Plugin http-ssl-auth specified but module artillery-plugin-http-ssl-auth could not be found (MODULE_NOT_FOUND) warn
```
which ends up raising `EPROTO` errors.

I then tried to install the `http-ssl-auth` plugin (which I found [here](https://www.npmjs.com/package/artillery-plugin-http-ssl-auth)). This led me to the following result: 

```
Unknown phase spec definition, skipping.
{}
This should not happen
⠋ /home/perftest/spinpay-performance-tests/node_modules/artillery-plugin-http-ssl-auth/index.js:37
  this._activated = (pro !== null && pro.isActivatedSync());
                                         ^

TypeError: pro.isActivatedSync is not a function
    at new SSLClientAuthPlugin (/home/perftest/spinpay-performance-tests/node_modules/artillery-plugin-http-ssl-auth/index.js:37:42)
    at Launcher.initPlugins (/home/perftest/spinpay-performance-tests/node_modules/artillery/lib/launch-platform.js:195:31)
    at async Launcher.run (/home/perftest/spinpay-performance-tests/node_modules/artillery/lib/launch-platform.js:336:5)
```

Am I missing something?

**Comment by hassy** [comment]
@elarrat that package is no longer maintained, the plugin is just part of Artillery Pro itself now. As long as you run your test with Artillery Pro, it should just work.

**Comment by elfakamal** [comment]
Hello @hassy 
what about non pro version ?
