### ISSUE TITLE
Lambda VPC issue with security-group-ids,subnet-ids

### ISSUE THREAD

**Issue by kmfreas** [artilleryio/artillery#1730]
I'm trying to run my artillery test in Lambda but connected in a VPC. I'm following the docs, which say the params `security-group-ids`,  `subnet-ids` are supposed to be [comma-separated lists of subnet IDs and security group IDs to configure Lambdas to run in a VPC](https://www.artillery.io/docs/guides/guides/command-line#:~:text=Comma%2Dseparated%20lists%20of%20subnet%20IDs%20and%20security%20group%20IDs%20to%20configure%20Lambdas%20to%20run%20in%20a%20VPC).

The command I'm running (with my values substituted for `xxx`)
`artillery run artillery.yml --platform aws:lambda --platform-opt region=us-east-1 --count 1 --platform-opt security-group-ids=sg-xxx --platform-opt subnet-ids=subnet-xxx,subnet-xxx,subnet-xxx`

Output:
```shell
NOTE: AWS Lambda support is experimental. Not all Artillery features work yet.
For details please see https://docs.art/aws-lambda

λ Creating AWS Lambda function...
- Bundling test data
  - artillery.yml
  - custom.js
- Installing dependencies
- Creating zip package
Preparing AWS environment...
⠏ node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

MultipleValidationErrors: There were 2 validation errors:
* InvalidParameterType: Expected params.VpcConfig.SecurityGroupIds to be an Array
* InvalidParameterType: Expected params.VpcConfig.SubnetIds to be an Array
    at ParamValidator.validate (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:40:28)
    at Request.VALIDATE_PARAMETERS (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/event_listeners.js:166:42)
    at Request.callListeners (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/event_listeners.js:120:11
    at finish (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/config.js:396:7)
    at /home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/config.js:414:9
    at SharedIniFileCredentials.get (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/credentials.js:127:7)
    at getAsyncCredentials (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/config.js:408:24)
    at Config.getCredentials (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/config.js:428:9) {
  code: 'MultipleValidationErrors',
  errors: [
    InvalidParameterType: Expected params.VpcConfig.SecurityGroupIds to be an Array
        at ParamValidator.fail (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:50:37)
        at ParamValidator.validateType (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:233:10)
        at ParamValidator.validateList (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:100:14)
        at ParamValidator.validateMember (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:91:21)
        at ParamValidator.validateStructure (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:76:14)
        at ParamValidator.validateMember (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:89:21)
        at ParamValidator.validateStructure (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:76:14)
        at ParamValidator.validateMember (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:89:21)
        at ParamValidator.validate (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:34:10)
        at Request.VALIDATE_PARAMETERS (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/event_listeners.js:166:42) {
      code: 'InvalidParameterType',
      time: 2022-12-14T09:36:40.462Z
    },
    InvalidParameterType: Expected params.VpcConfig.SubnetIds to be an Array
        at ParamValidator.fail (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:50:37)
        at ParamValidator.validateType (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:233:10)
        at ParamValidator.validateList (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:100:14)
        at ParamValidator.validateMember (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:91:21)
        at ParamValidator.validateStructure (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:76:14)
        at ParamValidator.validateMember (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:89:21)
        at ParamValidator.validateStructure (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:76:14)
        at ParamValidator.validateMember (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:89:21)
        at ParamValidator.validate (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/param_validator.js:34:10)
        at Request.VALIDATE_PARAMETERS (/home/krezfreas/.nvm/versions/node/v18.12.1/lib/node_modules/artillery/node_modules/aws-sdk/lib/event_listeners.js:166:42) {
      code: 'InvalidParameterType',
      time: 2022-12-14T09:36:40.462Z
    }
  ],
  time: 2022-12-14T09:36:40.462Z
}

Node.js v18.12.1
```

```
$ artillery version
Artillery Core: 2.0.0-27
Artillery Pro:  not installed (https://artillery.io/product)

Node.js: v18.12.1
OS:      linux
```

**Comment by hassy** [comment]
thank you for the bugc report @kmfreas! we're looking into what looks like a similar issue in https://github.com/artilleryio/artillery/issues/1649#issuecomment-1334537957

cc @juanig1

**Comment by juanig1** [comment]
Hey, Thanks for the report!
This should be fixed in the next version ([pr](https://github.com/artilleryio/artillery/pull/1737))
