### ISSUE TITLE
Lambda: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by adamfisher** [artilleryio/artillery#1739]
This is a slight continuation of #1649 where I specified this command:

```shell
artillery run --platform aws:lambda --platform-opt memory-size=2048 --platform-opt "region=us-east-1" --platform-opt "memory-size=128" --environment env1 artillery-test.yml
```

But I now get this error trying to run lambda as shown below. What is the `path` referring to in this output? Nothing in the output of `artillery run --help` mentioned anything about a `path`.

```shell
λ Creating AWS Lambda function...
- Bundling test data
C:\Users\17077\AppData\Roaming\npm\node_modules\artillery\node_modules\async\dist\async.js:222
    throw error;
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at validateString (node:internal/validators:163:11)
    at Object.resolve (node:path:171:9)
    at C:\Users\17077\AppData\Roaming\npm\node_modules\artillery\lib\create-bom\create-bom.js:196:18
    at Array.forEach (<anonymous>)
    at resolvePayloadPaths (C:\Users\17077\AppData\Roaming\npm\node_modules\artillery\lib\create-bom\create-bom.js:194:21)
    at getVariableDataFiles (C:\Users\17077\AppData\Roaming\npm\node_modules\artillery\lib\create-bom\create-bom.js:217:5)
    at nextTask (C:\Users\17077\AppData\Roaming\npm\node_modules\artillery\node_modules\async\dist\async.js:5327:14)
    at next (C:\Users\17077\AppData\Roaming\npm\node_modules\artillery\node_modules\async\dist\async.js:5334:9)
    at C:\Users\17077\AppData\Roaming\npm\node_modules\artillery\node_modules\async\dist\async.js:972:16 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v19.0.0
```

**Comment by adamfisher** [comment]
I saw a similar issue #733 but I verified the `artillery-test.yml` file is in the same directory as where I am running the command from.

**Comment by juanig1** [comment]
Hey, happy holidays!
Sorry I missed this issue. 

Can't replicate this now but seems the error comes from artillery failling to get the correct path to the test files.

Will try tomorrow with my windows setup and let you know how it goes.

**Comment by isaacamehgreg** [comment]
any solution to this issue
