### ISSUE TITLE
'Callback was already called' when trying to capture WS response

### ISSUE THREAD

**Issue by diegofeans** [artilleryio/artillery#1825]
Version info: 
```
artillery/2.0.0-30 darwin-x64 node-v19.4.0
```

Running this command: 
```
artillery run --config ./config.yml -e functional script.yml --output reports/script.json
```

I'm trying to capture the server response after sending a String through a WebSocket. I know the server is answering the right way because I am storing the response in a variable and then printing it using a console.log in a JS function.

The problem is that although I can capture the response, the tests breaks:

```
- send:
    payload: "My string to the server"
    capture:
       - regexp: "[^\n]+"
         as: "server_response"
```

I'm using that RegExp to get the full response (it is a string).
The error i get is the following:

```
worker error, id: 1 Error: Callback was already called.
    at /Users/myuser/artilleryws/node_modules/async/dist/async.js:969:32
    at captured (/Users/myuser/artilleryws/node_modules/@artilleryio/int-core/lib/engine_ws.js:94:18)
    at /Users/diegofeans/myuser/node_modules/@artilleryio/int-commons/engine_util.js:488:16
    at /Users/diegofeans/myuser/node_modules/async/dist/async.js:473:16
    at replenish (/Users/myuser/artilleryws/node_modules/async/dist/async.js:1009:25)
    at /Users/myuser/artilleryws/node_modules/async/dist/async.js:1019:9
    at eachLimit$1 (/Users/myuser/artilleryws/node_modules/async/dist/async.js:3199:24)
    at Object.<anonymous> (/Users/myuser/artilleryws/node_modules/async/dist/async.js:1049:16)
    at Object.captureOrMatch (/Users/myuser/artilleryws/node_modules/@artilleryio/int-commons/engine_util.js:404:9)
    at WebSocket.messageHandler (/Users/myuser/artilleryws/node_modules/@artilleryio/int-core/lib/engine_ws.js:68:16)
```

I know that the capture is what is causing the problem, because if I remove it, the test works fine.

**Comment by diegofeans** [comment]
@hassy

**Comment by hassy** [comment]
hi @diegofeans, the WebSocket engine does not support using `capture`

**Comment by diegofeans** [comment]
Is not? @hassy https://github.com/artilleryio/artillery/pull/917

**Comment by ChangHoon-Sung** [comment]
I'm having the same problem. Are there any other updates or changes related to WS capture or handler?

**Comment by Beliefg** [comment]
Is capture support or not? #917 indicates that it is.
