### ISSUE TITLE
Unable to run artillery with yarn 3.4.1

### ISSUE THREAD

**Issue by zach-betz-hln** [artilleryio/artillery#1863]
## Minimal Reproducible Example (MRE) GitHub Repo

https://github.com/zach-betz-hln/mre-artillery-yarn

## Steps to Reproduce

1. Confirm yarn version is 3.4.1

        yarn -v

1. Make empty dir and change to it

        mkdir mre-artillery-yarn
        cd mre-artillery-yarn

1. Init a yarn project

        yarn init

1. Install artillery

        yarn add artillery@^2.0.0-30

1. Run help

        yarn run artillery help

1. Observe error

## What I Expected to Happen

```
% yarn run artillery help           
(node:37814) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Cloud-scale load testing

VERSION
  artillery/2.0.0-30 darwin-arm64 node-v18.14.0

USAGE
  $ artillery [COMMAND]

TOPICS
  aws  run tests on AWS
  pro  deploy and manage Artillery Pro

COMMANDS
  dino    here be dinosaurs
  help    display help for artillery
  quick   run a simple test without writing a test script
  report  generate a HTML report from a JSON log produced with artillery run
  run     run a test script locally
```

## Instead, This Happened

```
% yarn run artillery help 
(node:37490) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/zachary.betz/dev/mre-artillery-yarn/.pnp.cjs:16179
      Error.captureStackTrace(firstError);
            ^

Error: artillery tried to access @oclif/errors, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @oclif/errors (via "@oclif/errors/handle")
Required by: artillery@npm:2.0.0-30 (via /Users/zachary.betz/dev/mre-artillery-yarn/.yarn/cache/artillery-npm-2.0.0-30-421107f07d-74bfa4a090.zip/node_modules/artillery/bin/)

Require stack:
- /Users/zachary.betz/dev/mre-artillery-yarn/.yarn/cache/artillery-npm-2.0.0-30-421107f07d-74bfa4a090.zip/node_modules/artillery/bin/run
    at require$$0.Module._resolveFilename (/Users/zachary.betz/dev/mre-artillery-yarn/.pnp.cjs:16179:13)
    at require$$0.Module._load (/Users/zachary.betz/dev/mre-artillery-yarn/.pnp.cjs:16029:42)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at main (/Users/zachary.betz/dev/mre-artillery-yarn/.yarn/cache/artillery-npm-2.0.0-30-421107f07d-74bfa4a090.zip/node_modules/artillery/bin/run:28:12)

Node.js v18.14.0
```

## Potential Workaround

Install missing packages?

```
yarn add @oclif/errors @oclif/help
```

**Comment by hassy** [comment]
thank you for the detailed report **and** a reproducible example @zach-betz-hln! 🙏

**Comment by zach-betz-hln** [comment]
@hassy Sure thing.

If it helps, here's my system info:

```
System:
  OS: macOS 13.2.1
  CPU: (10) arm64 Apple M1 Max
Binaries:
  Node: 18.14.0 - ~/bin/node-v18.14.0-darwin-arm64/bin/node
  Yarn: 3.4.1 - ~/bin/node-v18.14.0-darwin-arm64/bin/yarn
  npm: 9.3.1 - ~/bin/node-v18.14.0-darwin-arm64/bin/npm
```

**Comment by hassy** [comment]
@zach-betz-hln that Yarn version doesn't look right. Are you Yarn v2?

**Comment by zach-betz-hln** [comment]
@hassy It's a valid yarn version. I'm using it on other projects with no issue. 

Releases: https://github.com/yarnpkg/berry/releases

Docs: https://yarnpkg.com/getting-started/install

**Comment by hassy** [comment]
ah I see thanks. Didn't see it on npm!

**Comment by zach-betz-hln** [comment]
Hi @hassy - I appreciate you looking into this. 

I've since moved on to doing my load testing with [k6](https://k6.io/docs/). Feel free to deprioritize this issue, or close it, if you like.

**Comment by bdruth** [comment]
Running into this today as well. I can use `nodeLinker: node-modules`, but it doesn't work with `pnp`.
