### ISSUE TITLE
playwright engine Getting errors.Cannot read properties of undefined (reading 'goto'): 

### ISSUE THREAD

**Issue by Romarionijim** [artilleryio/artillery#2727]
Version info: 
```
<version>

"artillery": "^2.0.11",
  "artillery-engine-playwright": "^1.8.0",

Running this command: 
```
<command>
```
npx artillery run LoginFlowPerfTest.yml 
OR
BASE_URL=https://www.saucedemo.com npx artillery run LoginFlowPerfTest.yml 

I expected to see this happen:

load test for this website when navigating to it

Instead, this happened:

 I get the following error:
errors.Cannot read properties of undefined (reading 'goto'): ................... 1
vusers.created: ................................................................ 1
vusers.created_by_name.0: ...................................................... 1
vusers.failed: ................................................................. 1


Warning: multiple batches of metrics for period 
All VUs finished. Total time: 1 second

--------------------------------
Summary report @ 19:14:23(+0300)
--------------------------------

errors.Cannot read properties of undefined (reading 'goto'): ................... 1
vusers.created: ................................................................ 1
vusers.created_by_name.0: ...................................................... 1
vusers.failed: ................................................................. 1


Files being used:
```
LoginPage:

`import { expect } from "@playwright/test";
import { BasePage } from "./BasePage";

export class LoginPage extends BasePage {
  private userNameField = '#user-name';
  private passwordField = '#password';
  private loginButton = '#login-button'

  public async login(userName: string = process.env.USERNAME as string, password: string = process.env.PASSWORD as string) {
    await this.fillText(this.userNameField, userName);
    await this.fillText(this.passwordField, password);
    await this.clickElement(this.loginButton);
  }

  public async validateUrl(url: string) {
    const currentUrl = await this.getPageUrl();
    expect(currentUrl).toContain(url);
  }
}`

loginFlow.ts (proccessor):

`import { LoginPage } from "../../ui-automation/pages/LoginPage";

export async function loginFlow({ page }) {
  let loginPage = new LoginPage(page)
  await loginPage.loadApp();
  await loginPage.login();
}
`

yml file test:

`config:
  target: https://www.saucedemo.com/
  engines:
    playwright: {}
  processor: '../../../artillery/processors/LoginFlow.ts'
scenarios:
  - engine: playwright
    testFunction: 'loginFlow'`

**Comment by bernardobridge** [comment]
The processor function you export (`loginFlow`) needs to follow Artillery's function signature (https://www.artillery.io/docs/reference/engines/playwright#test-function-api). Try something like:


```typescript
import { LoginPage } from "../../ui-automation/pages/LoginPage";

export async function loginFlow(page) {
  let loginPage = new LoginPage(page)
  await loginPage.loadApp();
  await loginPage.login();
}
```

---
Unrelated, but I noticed you seem to be installing the `artillery-engine-playwright` package. There's no need to do that, as Artillery already includes it by default.

**Comment by Romarionijim** [comment]
@bernardobridge I tried to adjust it and run it again,it still has an issue reading from an env file, it reads the user name and password from the env file, again, these test pass without any issues in ui tests and the env is defined and credentials are read but for some reason artillery is not picking them out i get the following error:

`
⠏ locator.fill: value: expected string, got undefined
    at LoginPage.fillText (/Users/romario/Desktop/pw-projects/ui-automation/pages/BasePage.ts:31:26)
    at LoginPage.login (/Users/romario/Desktop/pw-projects/ui-automation/pages/LoginPage.ts:10:5)
    at loginFlow (/Users/romario/Desktop/pw-projects/artillery/processors/LoginFlow.ts:7:3)
    at async Array.scenario (/Users/romario/Desktop/pw-projects/node_modules/artillery-engine-playwright/index.js:340:11)
--------------------------------------
Metrics for period to: 21:00:00(+0300) (width: 2.6s)
--------------------------------------`


for a work around I had to type these username and password hardcoded like this:
`import { Page } from "@playwright/test";
import { LoginPage } from "../../ui-automation/pages/LoginPage";

export async function loginFlow(page:Page) {
  let loginPage = new LoginPage(page)
  await loginPage.loadApp();
  await loginPage.login('secret_sauce','secret_sauce');
} 
`


why is it not reading from the env file?

**Comment by bernardobridge** [comment]
@Romarionijim you can use the `--dotenv` [flag](https://www.artillery.io/docs/reference/cli/run#options) to provide a path to a dotenv file for Artillery to load.

**Comment by Romarionijim** [comment]
@bernardobridge I still not have tried this suggestion but this is still a workaround, if I'm running the test in CI I would only reference the env variables that are stored as secrets and that's it, I think it's an overhead specifying paths since it is a place for errors - this should read the dotenv file.
