### ISSUE TITLE
Getting TestDataSyncFailure some times when running on AWS Lambda

### ISSUE THREAD

**Issue by Panzki** [artilleryio/artillery#3260]
Version info: 
```
VERSION INFO:

Artillery: 2.0.16
Node.js:   v20.12.0
OS:        darwin
```

Running this command: 
```
npx artillery run-lambda --config "/test/project/root/artillery-config.yml" --variables '{"NR_LICENSE_KEY":{}}' --environment preview --region eu-west-1 --count 15 scenario.yml
```

I expected to see this happen:

Artillery executes the given scenario reliably every time.

Instead, this happened:

About 50% of the time Artillery fails with the following error message:
```
A Lambda function has exited with an error. Reason: TestDataSyncFailure
{
  err: {
    message: 'Number of files in metadata.json (3) does not match number of files (8) in local directory! Something went wrong!',
    stack: 'Error: Number of files in metadata.json (3) does not match number of files (8) in local directory! Something went wrong!\n' +
      '    at syncTestData (/artillery/a9-handler-dependencies.js:36:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async Runtime.handler (/artillery/a9-handler-index.js:70:5)'
  }
}
```

I could not reproduce the error reliably, sometimes it occurred some time everything is fine. It looks like there are already some files in the test data directory on the local files system of the Lambda function. The problem might be triggered if the AWS Lambda execution context is reused. The [AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtime-environment.html) state the following:

> Each execution environment provides between 512 MB and 10,240 MB, in 1-MB increments, of disk space in the /tmp directory. **The directory content remains when the execution environment is frozen, providing a transient cache that can be used for multiple invocations**. You can add extra code to check if the cache has the data that you stored.

Could you please have a look into this problem? If you need more information I'm happy to provide what's necessary.

**Comment by bernardobridge** [comment]
Hi @Panzki .

Thanks for reporting the issue. I'll be taking a look at it. Is this happening with a specific test? If you could share which files are being bundled with the test, and the contents of the test script, that could help us get started. Thank you!

**Comment by longbeom** [comment]
I've had the same problem,
I solved it by deleting the Lambda function and running it.

**Comment by nicholas-c** [comment]
👋 

Getting this error when generally pushing the `--count` number higher, the higher it goes the more likely it is to occur periodically. Cancelling, and re-running tends to just re-roll if it happens again or not

```
~/dev/algolia-load-test » artillery run-lambda --region=us-east-1 --memory-size=8000 load-test.yml --count=125
Test run id: [redacted]
λ Preparing AWS Lambda function...
Test bundle contents:
┌───────────────┬──────┬───────┐
│ Name          │ Type │ Notes │
├───────────────┼──────┼───────┤
│ load-test.yml │ file │       │
└───────────────┴──────┴───────┘

 - Lambda function: artilleryio-v2-0-20-arm64-4e075146bdb4d83955169e117b8506a8
 - Region: us-east-1
 - AWS account: [redacted]
 
[b8ebb3bd-d34a-48b3-b744-8b8f1198f50c]: A Lambda function has exited with an error. Reason: TestDataSyncFailure
{
  err: {
    message: 'Number of files in metadata.json (2) does not match number of files (7) in local directory! Something went wrong!',
    stack: 'Error: Number of files in metadata.json (2) does not match number of files (7) in local directory! Something went wrong!\n' +
      '    at syncTestData (/artillery/a9-handler-dependencies.js:36:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async Runtime.handler (/artillery/a9-handler-index.js:70:5)'
  }
}
```
