### ISSUE TITLE
Issue with setting scenario-level hooks

### ISSUE THREAD

**Issue by amalhotragannett** [artilleryio/artillery#478]
I created a config.yml file
```config:
  processors: "./my-functions.js"
  environments:
    staging:
      target: "https://test.com"
      phases:
        - duration: 30
          arrivalRate: 50
          
    
scenarios:
  - name: "Test Artillery"
    flow:
      - log: "Current Environment is set to: {{ $environment }}"
      - post:
          url: "/v1/graphql"
          beforeRequest: "setJSONBody"
          body: 'query {asset(id: "")}'
          headers:
            content-type: "application/graphql"
            x-api-key: "token"
            x-sitecode: "xxx"
```

Then i created a my-function.js
```'use strict';

module.exports = {
  setJSONBody: setJSONBody
};

function setJSONBody(requestParams, response, context, ee, next) {
  console.log("Method is called");
  return next(); // MUST be called for the scenario to continue
}
```

After executing the scenario I get an error:
```
artillery run -e staging config.yml
Started phase 0, duration: 30s @ 11:15:03(-0400) 2018-05-24
⠋ Current Environment is set to: staging
/usr/local/lib/node_modules/artillery/core/lib/engine_http.js:204
        let processFunc = config.processor[functionName];
                                          ^

TypeError: Cannot read property 'setJSONBody' of undefined
    at iteratee (/usr/local/lib/node_modules/artillery/core/lib/engine_http.js:204:43)
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:181:20
    at iterate (/usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:214:22)
    at f (/usr/local/lib/node_modules/artillery/core/lib/engine_http.js:200:11)
    at fn (/usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:746:34)
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:1213:16
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:166:37
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:706:43
```

**Comment by amalhotragannett** [comment]
The issue was tag `processors` should be replaced with `processor`
