### ISSUE TITLE
cannot install due to nomnom@1.5.2: Package no longer supported

### ISSUE THREAD

**Issue by songpr** [artilleryio/artillery#602]
cannot install due to nomnom@1.5.2: Package no longer supported

**Comment by hassy** [comment]
`nomnom` is a dependency of a dependency, so resolving this may take a while. Could you post the exact error message you're seeing + environment information (OS, Node.js version, npm version) please? Are you unable to install `artillery` altogether, or are you seeing an npm warning?

**Comment by sumiitmalik** [comment]
getting the same warning
$ npm install -g artillery
npm WARN deprecated nomnom@1.5.2: Package no longer supported. Contact support@npmjs.com for more info.
C:\Users\sumit.malik\AppData\Roaming\npm\artillery -> C:\Users\sumit.malik\AppData\Roaming\npm\node_modules\artillery\bin\artillery
C:\Users\sumit.malik\AppData\Roaming\npm
`-- artillery@1.6.0-26

$ artillery -V
C:\Users\sumit.malik\AppData\Roaming\npm\node_modules\artillery\node_modules\csv-parse\lib\index.js:36
    super({...{readableObjectMode: true}, ...opts})
           ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\sumit.malik\AppData\Roaming\npm\node_modules\artillery\lib\commands\run.js:12:13)

I am using the windows 7, node v7.8.0, npm 4.2.0
