### ISSUE TITLE
"ReferenceError: data is not defined" while running 3rd concurrent test (Artillery Pro)

### ISSUE THREAD

**Issue by sparkida** [artilleryio/artillery#654]
This is occurring only on the third cluster while attempting to run 3 concurrent tests with 20 tasks each.

```
Checking ECS cluster...
Checking Artillery Pro backend...
Acquiring queue lock...
ECS task does not exist, creating...
Checking test files...
Reading test metadata...
Preparing the test...
/home/nick/fox/load/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

ReferenceError: data is not defined
    at Response.ecs.runTask (/home/nick/fox/load/node_modules/artillery-pro/lib/commands/run-cluster.js:16:14399)
    at Request.<anonymous> (/home/nick/fox/load/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/home/nick/fox/load/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/nick/fox/load/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/nick/fox/load/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/nick/fox/load/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/nick/fox/load/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/nick/fox/load/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/nick/fox/load/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/nick/fox/load/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/nick/fox/load/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/home/nick/fox/load/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/nick/fox/load/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/nick/fox/load/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/nick/fox/load/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/nick/fox/load/node_modules/aws-sdk/lib/state_machine.js:26:10
```

Let me know what additional info I can provide to you.

**Comment by hassy** [comment]
This should certainly not be happening! Just to confirm - you're running 3 different tests on 3 different clusters at the same time? Does this happen consistently or only now and then?

**Comment by sparkida** [comment]
@hassy It's happening consistently with the third test.

The test manages to start some, but not all tasks, so I have to manually stop them. I've tried running at different intervals on different clusters, but have not tried reducing the task count to see if that would have something to do with it.

I'm happy to try some things from my end if you have any ideas.
