### ISSUE TITLE
--overrides not valid json on Windows OS

### ISSUE THREAD

**Issue by joszo** [artilleryio/artillery#710]
Hello,

I've prepared scripts for running tests, and it seems that is the problem with that command on Windows.

https://artillery.io/blog/end-to-end-performance-testing-microservices

```
artillery run --config ./services/auth-service/config.yaml --overrides "$(cat ./services/auth-service/overrides.slos.json)" -e dev ./services/auth-service/login.yaml
```

In my code it looks like this:

Example 1:
```
	execSync(
			`artillery run --config config/config.yaml --overrides "$(cat phases/phases.slos.json)" -o reports/json/${reportName}_${temporary} scenarios/${fileName}`,
			{ stdio: 'inherit' }
		);
```

First I thought that there is a problem with: 

```
 "$(cat phases/phases.slos.json)"
```

So I decide to add varaiable with json to my script:

```
 const json = {
        "config": {
            "phases": [
                {
                    "duration": 1,
                    "arrivalRate": 1,
                    "name": "Stress test of application 1 users per 1 second"
                }
            ]
        }
    }
```

And then I rewrite the same command:

```
    const test = "artillery run --config config/config.yaml --overrides " + "'" + JSON.stringify(json) + "'" + " -o reports/json/" + reportName + "_" + temporary + " scenarios/" + fileName
```

So my execSync looks like:

Example 2:
```
		execSync(
			test,
			{ stdio: 'inherit' }
		);
```

On MacOS both Example 1 & 2 work correctly but on Windows, there is always a problem with it...

```
$ npm run artillery createUser.yaml

> artillery C:\Users\Dawid\Desktop\qa_artillery
> node src/artillery.js "createUser.yaml"

win32 - CONSOLE LOG FOR VERSION OF OS

artillery run --config config/config.yaml --overrides '{"config":{"phases":[{"duration":1,"arrivalRate":1,"name":"Stress test of application 1 users per 1 second"}]}}' -o reports/json/createUser_29_4_2019_13_34_57 scenarios/createUser.yaml CONSOLE LOG OF RUN COMMAND

Error: The values of --overrides does not seem to be valid JSON.
child_process.js:661
   throw err;
   ^

Error: Command failed: artillery run --config config/config.yaml --overrides '{"config":{"phases":[{"duration":1,"arrivalRate":1,"name":"Stress test of application 1 users per 1 second"}]}}' -o reports/json/createUser_29_4_2019_13_34_57 scenarios/createUser.yaml
   at checkExecSyncError (child_process.js:621:11)
   at execSync (child_process.js:658:15)
   at runArtilleryConfig (C:\Users\Dawid\Desktop\qa_artillery\src\artillery.js:43:9)
   at Object.<anonymous> (C:\Users\Dawid\Desktop\qa_artillery\src\artillery.js:57:1)
   at Module._compile (internal/modules/cjs/loader.js:774:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
   at Module.load (internal/modules/cjs/loader.js:641:32)
   at Function.Module._load (internal/modules/cjs/loader.js:556:12)
   at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
   at internal/main/run_main_module.js:17:11 {
 status: 1,
 signal: null,
 output: [ null, null, null ],
 pid: 18060,
 stdout: null,
 stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zinio@1.0.0 artillery: `node src/artillery.js "createUser.yaml"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zinio@1.0.0 artillery script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dawid\AppData\Roaming\npm-cache\_logs\2019-05-29T11_34_58_488Z-debug.log
```

**Comment by MobyWare** [comment]
I'd love to see this addressed.

**Comment by hassy** [comment]
This looks like it's a Windows-specific quoting issue of some kind. I'd suggest trying with all spaces removed from `--overrides` to see if that works.

**Comment by guptapranay** [comment]
@hassy it doesn't work by removing spaces. If we remove spaces from after --overrides, artillery will consider the entire thing as argument which is not a valid one.
This is major show blocker for me too. Could you please help us out. 

https://stackoverflow.com/questions/58322330/running-a-command-from-gulp-file/58323351?noredirect=1#comment103008048_58323351

**Comment by hassy** [comment]
Does it also fail in the same way when run from the shell under Windows as opposed to running an Artillery process from JS code?

**Comment by guptapranay** [comment]
If I paste below command directly in terminal (VSCODE) in windows, it runs perfectly fine. Only when i run invoking thorough gulp, it fails.

artillery run -o report.json ./services/employeeServices/scenarios/create-employee-details.yml --config ./services/employeeServices/config.yml --overrides "$(cat ./services/employeeServices/overrides.slos.json)" -e staging

**Comment by hassy** [comment]
Okay, thanks @guptapranay. It's certainly not an Artillery issue then, but something going wrong with quoting in the Gulp/JS code that wraps Artillery.

**Comment by guptapranay** [comment]
Yes, not an artillery issue. But any suggestion you can provide, how to make that work with gulp in windows would be great help.

**Comment by CHANist** [comment]
I have face the same problem and found the solution, by escaping the json in Windows. As I do not own a Mac currently, I cannot test if it works well. But the following work for me. I am not using gulp, but plain js file. Here is how I make it to work. 

Just change the code from 
`const test = "artillery run --config config/config.yaml --overrides " + "'" + JSON.stringify(json) + "'" + " -o reports/json/" + reportName + "_" + temporary + " scenarios/" + fileName`

to 
`const test = "artillery run --config config/config.yaml --overrides " + "'" + JSON.stringify(json).replace(/\"/g, "\\\"") + "'" + " -o reports/json/" + reportName + "_" + temporary + " scenarios/" + fileName`

I know escaping `"` character, does not make sense anyway, but it seems this will work.

**Comment by mhardy** [comment]
Running into the same issue on Windows and finally got it working like this:

artillery run --overrides "{\"config\": {\"phases\": [{\"duration\": 10, \"arrivalRate\": 1}]}}" test-simple.yaml

**Comment by xoadrian** [comment]
Same thing happens for `--launch-config` argument. It has nothing to do with Gulp, I debugged it, run the command either from CLI, JS, etc ... the JSON string ends up in the artillery with all quotes removed .... 
What is passes:
```
{"cpu":4096,"memory":12288,"ulimits":[{"name":"nofile","softLimit":16384,"hardLimit":16384}]}
```
what gets there:
```
'{cpu:4096,memory:12288,ulimits:[{name:nofile,softLimit:16384,hardLimit:16384}]}'
```
All double quotes from the stringified JSON are just removed ... tried the above solution with escaping quotes or with replace, same thing ends up in artillery lib code.

I have also run the command using `shelljs.exec`, still the same, I believe it is an Artillery issue on Windows.

**Comment by hassy** [comment]
Thank you for taking the time to investigate @xoadrian! It sounds like a Windows shell quoting issue.

We'll look into it, but if anyone is able to come up with a workaround/recipe we can include in the docs (for cmd.exe and PowerShell -- seems like they're different), that'd be awesome 🙌 and would very likely earn you some nice Artillery swag as well as heaps of gratitude from Artillery users on Windows 🤠

**Comment by bruno-salapic** [comment]
this might help out https://github.com/artilleryio/artillery/issues/1002
