### ISSUE TITLE
The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by tirthaguha** [artilleryio/artillery#733]
```
$ artillery run test.yml
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:161:7)
    at 
    at arrayEach (\node_modules\lodash\lodash.js:516:11)

```
**My System info**
```
$ node -v
v10.15.3
$ npm -v
6.4.1
$ artillery --version

        ___         __  _ ____                  _
  _____/   |  _____/ /_(_) / /__  _______  __  (_)___  _____
 /____/ /| | / ___/ __/ / / / _ \/ ___/ / / / / / __ \/____/
/____/ ___ |/ /  / /_/ / / /  __/ /  / /_/ / / / /_/ /____/
    /_/  |_/_/   \__/_/_/_/\___/_/   \__, (_)_/\____/
                                    /____/

------------ Version Info ------------
Artillery: 1.6.0-28
Artillery Pro: not installed (https://artillery.io/pro)
Node.js: v10.15.3
OS: win32/x64
--------------------------------------

```

**Comment by tirthaguha** [comment]
Wrong path provided on my yml file, not a defect.
