### ISSUE TITLE
npm Install artillery -g fails with json error on windows with nodejs v12.13.1

### ISSUE THREAD

**Issue by tnokin** [artilleryio/artillery#776]
Any help appreciated, thanks !
Error is: 
//
248 silly resolveWithNewModule esprima@1.2.2 checking installable status
249 http fetch GET 304 https://registry.npmjs.org/underscore 146ms (from cache)
250 http fetch GET 304 https://registry.npmjs.org/static-eval 148ms (from cache)
251 silly fetchPackageMetaData error for static-eval@2.0.2 Unexpected end of JSON input while parsing near '...z"}},"2.0.1":{"name":'
252 silly pacote version manifest for underscore@1.7.0 fetched in 153ms
253 silly resolveWithNewModule underscore@1.7.0 checking installable status
254 timing stage:rollbackFailedOptional Completed in 1ms
255 timing stage:runTopLevelLifecycles Completed in 6847ms
256 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...z"}},"2.0.1":{"name":'
256 verbose stack     at JSON.parse (<anonymous>)
256 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
256 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
256 verbose stack     at runMicrotasks (<anonymous>)
256 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
257 verbose cwd c:\bdev
258 verbose Windows_NT 10.0.18362

**Comment by tnokin** [comment]
Solved after erasing C:\Users\xxx\AppData\Roaming\npm-cache, thanks
