### ISSUE TITLE
Issue when running behind proxy.

### ISSUE THREAD

**Issue by CalvinRodo** [artilleryio/artillery#849]
I'm using the [mitmproxy](https://mitmproxy.org/) in order to debug some tests. 

I'm running my tests with the following command: 

```bash
HTTP_PROXY=localhost:8080 HTTPS_PROXY=localhost:8080 artillery run key_submission.yml
```

I'm recieving the following results: 

```
Report @ 15:52:40(-0400) 2020-06-19
Elapsed time: 1 second
  Scenarios launched:  1
  Scenarios completed: 0
  Requests completed:  0
  Mean response/sec: 2.17
  Response time (msec):
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Errors:
    ECONNRESET: 1

All virtual users finished
Summary report @ 15:52:40(-0400) 2020-06-19
  Scenarios launched:  1
  Scenarios completed: 0
  Requests completed:  0
  Mean response/sec: 2.13
  Response time (msec):
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario counts:
    0: 1 (100%)
  Errors:
    ECONNRESET: 1
```

And when running with `DEBUG=http` I'm receiving the following error: 

```
     http Error: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.31.144:80 - Local (192.168.0.139:56636)
  http     at ClientRequest.onError (/usr/local/lib/node_modules/artillery/node_modules/tunnel-agent/index.js:177:17)
  http     at Object.onceWrapper (events.js:422:26)
  http     at ClientRequest.emit (events.js:315:20)
  http     at Socket.socketErrorListener (_http_client.js:467:9)
  http     at Socket.emit (events.js:315:20)
  http     at emitErrorNT (internal/streams/destroy.js:100:8)
  http     at emitErrorCloseNT (internal/streams/destroy.js:68:3)
  http     at processTicksAndRejections (internal/process/task_queues.js:84:21) +0ms
```

I've also tried with `--insecure` in case this was an issue with the self-signed cert that mitmproxy uses for HTTPS connections (And also the environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0` just to be sure).

Any insight on how to inspect traffic from Artillery?

**Comment by hassy** [comment]
hi @CalvinRodo. This looks to be an OS-level error, where the route to target IP `0.0.31.144` cannot be found. Are you able to make request via the proxy with another tool, e.g. `curl` or is the issue specific to Artillery?

**Comment by CalvinRodo** [comment]
I was able to make requests using the library node-fetch with an https-proxy-agent (again ignoring self-signed certs) and it worked fine.

I'll check it out with curl as well.
