### ISSUE TITLE
Multiple Random Number Values causes error

### ISSUE THREAD

**Issue by agalpin** [artilleryio/artillery#87]
Entering in to a get url's query string ?version={{{$randomNumber(0,2)}}}.{{{$randomNumber(1,20)}}}.{{{$randomNumber(1,9999)}}} throws a syntax error complaining about too many }.

This appears to be unsupported?

Also there appears to be no support for random entries in variables?

**Comment by hassy** [comment]
Sounds like a bug, thanks for the report!

**Comment by anthofo** [comment]
Same for me, if I use only one `$randomNumber` or `$randomString` it works like a charm, but if I use multiple random values:

```yaml
flow:
   - get:
       url: "/seller-informations?price={{ $randomNumber(1000, 20000) }}&lastName={{ $randomString(5) }}&zipCode={{ $randomNumber(10000, 40000) }}&id=73{{ $randomNumber(20, 10000) }}"
```

I get the following error : 

```bash
C:\[...]\npm\node_modules\artillery\node_modules\esprima\dist\esprima.js:1995                                                        
                throw this.unexpectedTokenError(token, message);                                                                                               
                ^                                                                                                                                              
Error: Line 1: Unexpected token }                                                                                                                              
    at ErrorHandler.constructError (C:\[...]\npm\node_modules\artillery\node_modules\esprima\dist\esprima.js:5012:22)                
    at ErrorHandler.createError (C:\[...]\npm\node_modules\artillery\node_modules\esprima\dist\esprima.js:5028:27)                   
    at Parser.unexpectedTokenError (C:\[...]\npm\node_modules\artillery\node_modules\esprima\dist\esprima.js:1985:39)                
    at Parser.throwUnexpectedToken (C:\[...]\npm\node_modules\artillery\node_modules\esprima\dist\esprima.js:1995:21)                
    at Parser.parsePrimaryExpression (C:\[...]\npm\node_modules\artillery\node_modules\esprima\dist\esprima.js:2366:38)              
    at Parser.inheritCoverGrammar (C:\[...]\npm\node_modules\artillery\node_modules\esprima\dist\esprima.js:2285:37)                 
    at Parser.parseLeftHandSideExpressionAllowCall (C:\[...]\npm\node_modules\artillery\node_modules\esprima\dist\esprima.js:2899:26)
    at Parser.inheritCoverGrammar (C:\[...]\npm\node_modules\artillery\node_modules\esprima\dist\esprima.js:2285:37)                 
    at Parser.parseUpdateExpression (C:\[...]\npm\node_modules\artillery\node_modules\esprima\dist\esprima.js:3004:26)               
    at Parser.parseUnaryExpression (C:\[...]\npm\node_modules\artillery\node_modules\esprima\dist\esprima.js:3048:26)                
```

**Comment by hassy** [comment]
Thanks @anthofo - fix to be available in the next release.
