### ISSUE TITLE
Errors when creating a report in html format

### ISSUE THREAD

**Issue by pbezpal** [artilleryio/artillery#871]
pbezpal@devops ~/r/t/l/artillery> sudo artillery report result.json 
Report generated: result.json.html
(node:2819065) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/usr/local/lib/node_modules/artillery/node_modules/opn/index.js:85:13)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
(node:2819065) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2819065) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

artillery version
Artillery: 1.6.1
Artillery Pro: not installed (https://artillery.io/pro)
Node.js: v10.19.0
OS: linux/x64

Node version
v10.19.0

**Comment by hassy** [comment]
Thanks @pbezpal, looks like it may be an error with trying to open the generated HTML file in the browser. Does `result.json.html` actually contain a report when that happens?

**Comment by pbezpal** [comment]
Yes @hassy 
![Снимок экрана от 2020-08-19 15-54-38](https://user-images.githubusercontent.com/49067808/90637186-5b876c80-e234-11ea-847f-33ca33c21b09.png)
