### ISSUE TITLE
DeprecationWarning: Got: "options.rejectUnauthorized" is now deprecated

### ISSUE THREAD

**Issue by RandScullard** [artilleryio/artillery#996]
I just installed artillery 1.7.0 for the first time, and when I have tls: rejectUnauthorized: false in my script, I get the following output:

```
/ (node:712) DeprecationWarning: Got: "options.rejectUnauthorized" is now deprecated, please use "options.https.rejectUnauthorized"
(Use `node --trace-deprecation ...` to show where the warning was created)
```

When I add the --trace-deprecation flag, I get this output:

```
/ (node:17564) DeprecationWarning: Got: "options.rejectUnauthorized" is now deprecated, please use "options.https.rejectUnauthorized"
    at Object.exports.default (C:\RDS\intelliv8\patents\LoadTest\node_modules\got\dist\source\utils\deprecation-warning.js:10:13)
    at normalizeArguments (C:\RDS\intelliv8\patents\LoadTest\node_modules\got\dist\source\core\index.js:652:42)
    at got (C:\RDS\intelliv8\patents\LoadTest\node_modules\got\dist\source\create.js:112:39)
    at done (C:\RDS\intelliv8\patents\LoadTest\node_modules\artillery\core\lib\engine_http.js:577:9)
    at C:\RDS\intelliv8\patents\LoadTest\node_modules\async\lib\async.js:52:16
    at iterate (C:\RDS\intelliv8\patents\LoadTest\node_modules\async\lib\async.js:260:24)
    at Object.async.forEachOfSeries.async.eachOfSeries (C:\RDS\intelliv8\patents\LoadTest\node_modules\async\lib\async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (C:\RDS\intelliv8\patents\LoadTest\node_modules\async\lib\async.js:214:22)
    at f (C:\RDS\intelliv8\patents\LoadTest\node_modules\artillery\core\lib\engine_http.js:268:11)
    at fn (C:\RDS\intelliv8\patents\LoadTest\node_modules\async\lib\async.js:746:34)

```

**Comment by hassy** [comment]
thank you @RandScullard!
